[project]
name = "pypiwrap"
description = "An API wrapper for the Python Package Index"
authors = [{ name = "Angel Carias", email = "lotta.dev@outlook.com" }]
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dynamic = ["version"]
dependencies = ["requests >= 2.32.0"]

[project.urls]
"Homepage" = "https://github.com/aescarias/pypiwrap"
"Changelog" = "https://github.com/aescarias/pypiwrap/blob/main/CHANGELOG.md"
"Documentation" = "https://pypiwrap.rtfd.io/"

[project.optional-dependencies]
docs = [
    "Sphinx >= 8.1.0",
    "sphinx-design >= 0.7.0",
    "furo >= 2025.12.19",
    "sphinx-copybutton >= 0.5.2",
]
tests = ["pytest-cov >= 7.0.0", "pytest >= 9.0.0", "tox >= 4.50"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]

[tool.setuptools.dynamic]
version = { attr = "pypiwrap.consts.__version__" }

[build-system]
requires = ["setuptools >= 80"]
build-backend = "setuptools.build_meta"
