[tox]
env_list =
    py3{10, 11, 12, 13, 14}
requires = 
    tox>=4.50.0

[testenv]
description = run the tests with pytest
package = wheel
wheel_build_env = .pkg
deps =
    pytest>=9
commands =
    pytest {tty:--color=yes} {posargs}
