name: Publish Documentation
on: 
  push:
    branches: [ main ]
jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install requirements
        run: |
          python3 -m pip install -e .[docs]
      - name: Build docs with Sphinx
        run: |
          sphinx-build docs/source _build      
          cp .gitignore _build/
      - name: Push Docs
        run: |
          git checkout -b gh-pages
          cp _build/* . -r
          touch .nojekyll
          git config --global user.name "aescarias"
          git config --global user.email "aescarias@users.noreply.github.com"
          git add .
          git commit -m ":memo: Updating docs for commit ${GITHUB_SHA}"
          git push deploy gh-pages
        shell: bash
