name: Publish Documentation
on: 
  push:
    branches: [ main ]
jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install requirements
        run: |
          python3 -m pip install -e .[docs]
      - name: Build docs with Sphinx
        run: |
          sphinx-build docs/source _build      
          mv .gitignore _build
      - name: Init Git
        run: |
          git checkout -b gh-pages
          git config --global user.name "aescarias"
          git config --global user.email "aescarias@users.noreply.github.com"
      - name: Push Docs
        run: |
          git rm -rf .
          mv _build/* . && rm _build -r
          touch .nojekyll
          git add .
          git commit -m ":memo: Updating docs for commit ${GITHUB_SHA}"
          git push origin gh-pages --force
        shell: bash
